services:
  bot:
    build:
      context: .
    image: ${IMAGE_NAME:-tgbot-manage-addresslist-mikrotik:local}
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./secrets/id_ed25519:/run/secrets/mikrotik_ssh_key:ro
      - ./secrets/known_hosts:/run/secrets/known_hosts:ro
